### ISSUE TITLE
hacPackTools-NACP: "Invalid file" error when performing a NACP -> XML conversion.

### ISSUE THREAD

**Issue by DarkMatterCore** [The-4n/hacPack#6]
This is the culprit:

https://github.com/The-4n/hacPack/blob/775b5d17f3c88d2c7543b082c5c4d5b9819b8012/hacPack-Tools/hacPackTools-NACP/nacp.hpp#L65

The program worked just fine after removing that struct member.

**Comment by The-4n** [comment]
Did you try building it from the source or using the releases?

**Comment by DarkMatterCore** [comment]
I built it from source using TDM-GCC under Windows 10. The total struct size ends up being 16388 (0x4004) bytes if that struct member isn't removed.

I used the Control.nacp from Super Mario Odyssey.

**Comment by DarkMatterCore** [comment]
As to why I removed that specific member: https://switchbrew.org/wiki/NACP_Format.

The full Control.nacp should always be 0x4000 bytes in size. Switchbrew doesn't mention an u32 field between `RequiredNetworkServiceLicenseOnLaunchFlag` and the last 0xDEC bytes.

**Comment by The-4n** [comment]
Switchbrew is true about size but not about the parameters
Source is still under development
There are new parameters that i didn't have enough time to add and i've pushed that commit by a mistake, so use the releases and it's fine

**Comment by DarkMatterCore** [comment]
No problem! I just wanted to point that out since part of my ongoing project uses code based on hptnacp.

Thanks for your contributions! They are a great source of knowledge.
